export const tripInfo = [
    {
        id:1,
        title: "Upper Mustang",
        link: "/",
        slug: "fgfg",
        img:'./assets/tripImg.png',
        imgA:'./assets/gautamBuddha.png',
        destination: "Upper Mustang",
        location: "Mustang/Nepal",
        cost: "$700",
        duration: "5 days",
        rating: 5,
         days:'7days/6 night',
    },  
    {
        id:2,
        title: "Upper Mustang",
        link: "/",
        slug: "sere",
        img:'./assets/tripImg.png',
        imgA:'./assets/buddha.png',
        destination: "Upper Mustang",
        location: "Mustang/Nepal",
        cost: "$700",
        duration: "5 days",
        rating: 3,
         days:'7days/6 night',
    },  
    {
        id:3,
        title: "Upper Mustang",
        link: "/",
        slug: "yuy",
        img:'./assets/tripImg.png',
        imgA:'./assets/taajmahal.png',
        destination: "Upper Mustang",
        location: "Mustang/Nepal",
        cost: "$700",
        duration: "5 days",
        rating: 4,
         days:'7days/6 night',
    },  
    {
        id:4,
        title: "Upper Mustang",
        link: "/",
        slug: "rtert",
        img:'./assets/tripImg.png',
        imgA:'./assets/buddha.png',
        destination: "Upper Mustang",
        location: "Mustang/Nepal",
        cost: "$700",
        duration: "5 days",
        rating: 3,
         days:'7days/6 night',
    },  
    {
        id:5,
        title: "Upper Mustang",
        link: "/",
        slug: "rtrg",
        img:'./assets/tripImg.png',
        imgA:'./assets/gautamBuddha.png',
        destination: "Upper Mustang",
        location: "Mustang/Nepal",
        cost: "$700",
        duration: "5 days",
        rating: 5,
         days:'7days/6 night',
    },  
    {
        id:6,
        title: "Upper Mustang",
        link: "/",
        slug: "sdrs",
        img:'./assets/tripImg.png',
        imgA:'./assets/taajmahal.png',
        destination: "Upper Mustang",
        location: "Mustang/Nepal",
        cost: "$700",
        duration: "5 days",
        rating: 4,
         days:'7days/6 night',
    },  
    {
        id:7,
        title: "Upper Mustang",
        link: "/",
        slug: "teuyt",
        img:'./assets/tripImg.png',
        imgA:'./assets/buddha.png',
        destination: "Upper Mustang",
        location: "Mustang/Nepal",
        cost: "$700",
        duration: "5 days",
        rating: 2,
         days:'7days/6 night',
    },  
    {
        id:8,
        title: "Upper Mustang",
        link: "/",
        slug: "yihk",
        img:'./assets/tripImg.png',
        imgA:'./assets/gautamBuddha.png',
        destination: "Upper Mustang",
        location: "Mustang/Nepal",
        cost: "$700",
        duration: "5 days",
        rating: 5,
        days:'7days/6 night',
    },  
        
    
]
export const tabData = [
    {
        id: '1',
        title: 'Tours'
    }, {
        id: '2',
        title: 'Flights'
    }, {
        id: '3',
        title: 'Hotels'
    }, {
        id: '4',
        title: 'Climbing'
    },

]